#ifndef _INCLUDE_ROLLINGSTOCK_FUNCTIONS_H
#define _INCLUDE_ROLLINGSTOCK_FUNCTIONS_H

#define TRAIN_FUNCTION_MOMENTARY 0
#define TRAIN_FUNCTION_TOGGLE 1
#define TRAIN_FUNCTION_SHORT 2
#define TRAIN_FUNCTION_LONG 3

#define TRAIN_FUNCTION_UNDEFINED 0
#define TRAIN_FUNCTION_HEADLIGHTS 2
#define TRAIN_FUNCTION_CABLIGHTS 3
#define TRAIN_FUNCTION_LOW_HORN 4
#define TRAIN_FUNCTION_HIGH_HORN 5
#define TRAIN_FUNCTION_UNUSED 0x3F


struct train_funcs {
  uint8_t type;
  uint8_t button:4;
  uint8_t state:4;
};


#endif